global using System;
global using System.Globalization;
global using AutoFrontline.Dependencies;
global using Dalamud.Plugin;
global using Dalamud.Bindings.ImGui;
global using ECommons.DalamudServices;
global using Dalamud.Interface;
global using ECommons.Logging;
global using ECommons;
global using ECommons.ImGuiMethods;
global using ECommons.SimpleGui;
global using ECommons.Configuration;
global using ECommons.Throttlers;
global using ECommons.Automation;
global using MirageUI;
global using static MirageUI.Ui.MirageLayout;
global using static AutoFrontline.Plugin;
